# Generated by Django 4.1.2 on 2023-04-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='admin_id',
        ),
    ]
